import { Inter } from 'next/font/google'
import './globals.css'
import NavbarMain from '@/app/NavBarMain/index'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='text-white'>
      <body className={inter.className}>
        <NavbarMain />
        {children}
      </body>
    </html>
  )
}